### PR TITLE
Port to Python 3 and Matplotlib

### PR DESCRIPTION
**Pull request by jspricke**

### CODE REVIEW

**Comment by andrewgee** [comment]
Hey @jspricke . This looks really good. Are you happy with where it's at? Ready to review and merge once you're done

**Comment by jspricke** [comment]
it's working fine for me, so would be great to see this merged :).

Could you release a new version afterwards as well? I could sponsor an 
upload to Debian as well, if you need one.

**Comment by jspricke** [comment]
@andrewgee anything I can help you with to get this merged?

**Comment by andrewgee** [comment]
Hi @jspricke. I'll aim to take a look today. Sorry for the delay as I've only just returned from a holiday

**Pull request merged**
